/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cartera_De_Clientes;

import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class EliminarCliente extends javax.swing.JFrame {
    
    //DECLARACION DE UNA VARIABLE DE MENU PARA ENLAZAR LAS CLASES Y PODER MANIPULAR LOS DATOS DE 
    //DE LA LISTA DE LA CLASE PRINCIPAL
    Menu funcionamiento = new Menu();
    
    /**
     * Creates new form EliminarCliente
     */
    //METODO CONSTURCTOR DE LA CLASE ELIMINAR CLIENTE CON INTERFZAS GRAFICA
    public EliminarCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        txtResultado.setText("Datos del cliente...");
        jScrollPane1.setViewportView(txtResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 310, -1));

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 120, 50));

        btnEliminar.setBackground(new java.awt.Color(0, 153, 153));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 120, 50));

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 310, -1));

        lblID.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID:");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 20));

        lblTitulo.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("ELIMINAR CLIENTE");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 140, 20));

        lblFondo.setBackground(new java.awt.Color(255, 255, 255));
        lblFondo.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 13)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cartera_De_Clientes/Recursos/Fondo.jpg"))); // NOI18N
        lblFondo.setToolTipText("");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //METODO DE LA ACCION PREDETERMIANDA DEL BOTON ELEMINAR DE LA CLASE ELIMINAR CLIENTE
    //QUE A TRAVES DEL METODO "eliminarCliente" DECLARADO EN LA CLASE MENU PRINCIPAL
    //ELIMINA LOS DATOS DEL CLIENTE CON COINCIDENCIA EN EL ID Y MUESTRA UN MENSAJE DE ELIMINACION
    //Y CIIERRA LA VENTANA Y VUELVE AL MENU PRINCIPAL
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            funcionamiento.eliminarCliente(Integer.parseInt(txtID.getText()));
            System.out.println("IDtxt: "+Integer.parseInt(txtID.getText()));
            JOptionPane.showMessageDialog(null, "ELIMINADO CORRECTAMENTE");
            funcionamiento.setVisible(true);
            dispose();
        }catch(Exception e){
            System.out.println("Error: "+ e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    //METODO DE LA ACCION PREDETERMINADA DEL BOTON VOLVER DE LA CLASE ELIMINAR CLIENTE
    //QUE VUELVE AL MENU PRINCIPAL Y CIERRA LA VENTANA ACTUAL
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        funcionamiento.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    //METODO DE TECLA LIBERADA DEL CUADRO DE TEXTO DE ID PARA BUSCAR LOS DATOS DE UN CLIENTE Y 
    //MOSTRARLOS EN UN AREA DE TEXTO A TRAVES DEL METODO APPED
    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        try{
            String datos[] = funcionamiento.buscarCliente(Integer.parseInt(txtID.getText()));
            txtResultado.setText("");
            for(int i = 0; i<datos.length; i++){
                txtResultado.append(datos[i]+"\n");
            }
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_txtIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
